import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce App Template - Next.js",
  description: "Complete template with user-login, user-authentication, shopping cart, checkout with Stripe, and Tailwindcss & DaisyUI styling. Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-screen-xl min-w-[300px] m-auto min-h-screen flex flex-col items-center p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
